# Generated by Django 3.1.6 on 2021-02-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people', models.IntegerField()),
                ('minutes', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
