# Generated by Django 3.1.6 on 2021-02-20 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210220_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='minutes',
            field=models.IntegerField(default=5),
        ),
    ]
