# Generated by Django 3.1.6 on 2021-02-20 22:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210220_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='minutes',
        ),
        migrations.AddField(
            model_name='group',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
